name: Build and Lint
permissions:
    contents: write
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        name: Lint
        steps:
            - uses: pnpm/action-setup@v4
              with: 
                  version: 10
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "19.x"
            - name: Build
              id: build
              run: |
                  pnpm install
                  pnpm run lint
    format:
        runs-on: ubuntu-latest
        name: Format
        steps:
            - uses: pnpm/action-setup@v4
              with: 
                  version: 10
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "19.x"
            - name: Build
              id: build
              run: |
                  pnpm install
                  pnpm run check-format
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
            - uses: pnpm/action-setup@v4
              with: 
                  version: 10
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "19.x"
            - name: Build
              id: build
              run: |
                  pnpm install
                  pnpm run build
